name: Matrix Configuration

on: 
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
          fail-fast: false
          max-parallel: 2
          matrix:
            os: [ubuntu-latest, ubuntu-20.04, windows-latest]
            images: [hello-world, alpine]
            # alpine image will not run on windows because it is excluded
            exclude:
              - images: alpine
                os: windows-latest
            # amd64/alpine only runs on ubuntu-20.04 because it is included
            include:
              - images: amd64/alpine
                os: ubuntu-20.04
        runs-on: ${{matrix.os}}
        steps:
            - name: Echo Docker Details
              run: docker info

            - name: Run Image on ${{matrix.os}}
              run: docker run ${{matrix.images}}

    # deploy-on-ubuntu:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Echo Docker Details
    #           run: docker info

    #         - name: Run Images
    #           run: docker run hello-world

    # deploy-on-windows:
    #     runs-on: windows-latest
    #     steps:
    #         - name: Echo Docker Details
    #           run: docker info

    #         - name: Run Images
    #           run: docker run hello-world

