# Note: Each job is runs on it's own virtual machine and by default if we not used needs keyword all jobs are run parallel
name: Multiple Job Example

on: 
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....REWR" >> dragon.txt

            #  To persists artifacts (if we want to access this artifact in another job use download artifact action in other jobs)
            - name: Upload Dragon text file
              uses: actions/upload-artifact@v4
              with:
                name: dragon-text-file
                # A file, directory or wildcard pattern that describes what to upload
                path: dragon.txt

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            # Download artifact which is uploaded in previous jobs
            - name: Download Dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt

    deploy_job_3:
        # Note: needs also accepts array if it depends on multiple jobs
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: Download Dragon text file
              uses: actions/download-artifact@v4
              with:
                name: dragon-text-file

            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying .....